import { Theme } from '@radix-ui/themes';
import { Inter } from 'next/font/google';

import NavBar from './navbar';

import '@/app/styles/globals.css';
import '@radix-ui/themes/styles.css';
import './theme-config.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.variable}>
        <Theme appearance='light' accentColor='violet'>
          <NavBar />
          <main className='p-5'>{children}</main>
        </Theme>
      </body>
    </html>
  );
}
