import { Container, Theme } from '@radix-ui/themes';
import { Inter } from 'next/font/google';

import AuthProvider from './auth/Provider';
import NavBar from './navbar';
import QueryClientProvider from './providers/QueryClientProvider';

import '@/app/styles/globals.css';
import '@radix-ui/themes/styles.css';
import './theme-config.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.variable}>
        <QueryClientProvider>
          <AuthProvider>
            <Theme appearance='light' accentColor='violet'>
              <NavBar />
              <main className='p-5'>
                <Container>{children}</Container>
              </main>
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
